
 && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' '

else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}
else if(estadoForm == estadoFB && cidadeForm == cidadeFB && tipoLeilaoForm == tipo_leilaoFB && propostaForm == propostaFB && tipoImovelForm == tipoFB && valorMinimoVendaForm >= vlr_de_vendaFB && valorMaximoAvaliacaoForm <= vlr_de_avaliacaoFB && ocupadoDesocupadoForm == situacaoFB && tipoLeilaoForm == ' ' && propostaForm == ' ' && tipoImovelForm == ' ' && valorMinimoVendaForm == 0.0 && valorMaximoAvaliacaoForm == 0.0 && ocupadoDesocupadoForm == ' ')  {}